Swipe: Add option to perform haptic feedback after threshold passed
afollestad/recyclical pull request #20
Opened 2019-07-26 16:09 UTC by ivaniskandar

Signed-off-by: Ivan Iskandar <iiiiskandar14@gmail.com>

### Guidelines 

1. You must run the `spotlessApply` task before commiting, either through Android Studio or with `./gradlew spotlessApply`.
2. A PR should be focused and contained. If you are changing multiple unrelated things, they should be in separate PRs.
3. A PR should fix a bug or solve a problem - something that only you would use is not necessarily something that should be published.
4. Give your PR a detailed title and description - look over your code one last time before actually creating the PR. Give it a self-review.

**If you do not follow the guidelines, your PR will be rejected.**

2019-07-28 03:00 UTC, afollestad requested changes

2019-07-28 03:00 UTC, afollestad commented on sample/src/main/java/com/afollestad/recyclicalsample/MainActivity.kt
> +        hapticFeedbackEnabled = true
I'd prefer having this as a method call, like 
```kotlin
... {
   hapticFeedbackEnabled()
}
```

2019-07-28 03:00 UTC, afollestad commented on swipe/src/main/java/com/afollestad/recyclical/swipe/SwipeAction.kt
> +  var hapticFeedbackEnabled = false
So, this should be private and there should be a method that sets it to true 🙂

2019-08-08 14:56 UTC, ivaniskandar commented
So @afollestad, how is it?

2019-08-09 00:21 UTC, afollestad commented
Can you rebase with this repo's master branch? I fixed the Travis CI build

2019-08-09 09:03 UTC, ivaniskandar commented
Done, now the checks is all green

2019-08-09 17:27 UTC, afollestad approved these changes
Thanks 👍

2019-08-09 17:27 UTC, merged